site_name: metwork/{{cookiecutter.repo}} doc
theme:
  name: 'material'
  logo: 'images/logo.png'
repo_url: https://github.com/metwork-framework/{{cookiecutter.repo}}
repo_name: 'GitHub'
plugins:
  - search
  - mkdocs-add-number-plugin:
      strict_mode: False
      order: 2
  - macros

markdown_extensions:
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - admonition
